title: SHREYA SHARMA
description: > # this means to ignore newlines until "baseurl:"
  I am a Bachelor's student at IIT (BHU) Varanasi. My main area of research is
  Applied Cryptography. My work addresses data privacy concerns and efficiency 
  in secure settings. 
permalink: ':title/'
baseurl: "/github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shreya Sharma # add your name
author-img: shreya.jpg # add your photo
about-author: Senior Undergrad in Electronics Engineering at IIT (BHU) Varanasi # add description
social-twitter: # add your Twitter handle
social-facebook:  # add your Facebook handle
social-github: shreya-28 # add your Github handle
social-linkedin: shreya-sharma-bb6203191 # add your Linkedin handle
social-email: shreyas.cd.ece17 [at] iitbhu.ac.in  # add your Email address
social-googlescholar: citations?user=k4YiMksAAAAJ&hl=en
cv-file: CVShreya.pdf
# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
